### ISSUE TITLE
More information in readme

### ISSUE THREAD

**Issue by alexchandel** [calculuswhiz/atom-GAS-x86_64-highlighter#1]
> This is the greatest assembly language of All Time

Could you expand on this a little, and maybe put some information in the readme on how this package differs from https://atom.io/packages/language-x86 (https://github.com/taylorlapeyre/language-x86) ?

**Comment by calculuswhiz** [comment]
There's information about the project in the link I provided, but yes, I can explain the difference on the README.

**Comment by calculuswhiz** [comment]
Ok. Done.
